In [2]:
## read image return array using cv
import cv2
im = cv2.imread("datasets/bop23_challenge/datasets/icbin/train_pbr/000001/rgb/000002.jpg")

In [1]:
import numpy as np
file = np.load("src/poses/predefined_poses/idx_all_level0_in_level2.npy")

In [9]:
obj_poses = np.load("src/poses/predefined_poses/obj_poses_level0.npy")
obj_poses

array([[[-1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -0.00000000e+00],
        [ 0.00000000e+00, -1.00000000e+00,  0.00000000e+00,
         -0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          1.00000000e+03],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[ 9.51058053e-01, -3.09012264e-01,  0.00000000e+00,
          2.84217094e-14],
        [ 2.62862646e-01,  8.09021733e-01, -5.25725275e-01,
         -5.68434189e-14],
        [ 1.62455557e-01,  4.99995257e-01,  8.50654416e-01,
          1.00000001e+03],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[-9.51058053e-01, -3.09012264e-01, -0.00000000e+00,
         -2.84217094e-14],
        [ 2.62862646e-01, -8.09021733e-01, -5.25725275e-01,
         -5.68434189e-14],
        [ 1.62455557e-01, -4.99995257e-01,  8.50654416e-01,
          1.00000001e+03],
        [ 0.00000000e+00,  0.00000000e+

In [13]:
import pandas as pd

df = pd.read_csv('datasets/bop23_challenge/datasets/tless/train_pbr_metaData.csv')


In [16]:
df["obj_id"] == 1

0         False
1         False
2         False
3         False
4         False
          ...  
199370    False
199371    False
199372    False
199373    False
199374    False
Name: obj_id, Length: 199375, dtype: bool

In [18]:
index_dataframe = np.arange(0, len(df))
index_dataframe[df["obj_id"] == 1]

array([  3002,   3021,   3040, ..., 199323, 199343, 199363])

In [2]:
import json
file_path = "datasets/bop23_challenge/results/cnos_exps/SAM_PBR_CustomSamAutomaticMaskGenerator_template_pbr0_aggavg_5_tless.json"
file = json.load(open(file_path, 'r'))

In [3]:
print(len(file))
print(file[0])

62623
{'scene_id': 1, 'image_id': 17, 'category_id': 1, 'bbox': [207, 196, 63, 67], 'score': 0.5460606217384338, 'time': 2.142730712890625, 'segmentation': {'counts': [111459, 18, 522, 18, 518, 24, 514, 29, 510, 33, 505, 36, 502, 40, 498, 43, 496, 45, 494, 47, 493, 47, 492, 50, 488, 53, 486, 56, 484, 57, 482, 59, 481, 60, 478, 63, 477, 63, 477, 63, 477, 65, 475, 65, 475, 65, 475, 66, 474, 66, 474, 67, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 69, 471, 69, 472, 68, 472, 67, 473, 67, 473, 67, 472, 68, 472, 68, 472, 68, 473, 67, 473, 66, 474, 66, 476, 64, 476, 64, 476, 63, 478, 62, 479, 59, 481, 59, 482, 57, 484, 55, 486, 54, 487, 52, 488, 52, 489, 50, 492, 47, 494, 45, 497, 42, 499, 38, 505, 33, 512, 27, 520, 17, 523, 17, 526, 10, 242220], 'size': [540, 720]}}


In [7]:
sum(file[0]["segmentation"]["counts"])

388800

In [ ]:
{'scene_id': 1, 'image_id': 17, 'category_id': 1, 'bbox': [207, 196, 63, 67], 'score': 0.5460606217384338, 'time': 2.142730712890625, 'segmentation': {'counts': [111459, 18, 522, 18, 518, 24, 514, 29, 510, 33, 505, 36, 502, 40, 498, 43, 496, 45, 494, 47, 493, 47, 492, 50, 488, 53, 486, 56, 484, 57, 482, 59, 481, 60, 478, 63, 477, 63, 477, 63, 477, 65, 475, 65, 475, 65, 475, 66, 474, 66, 474, 67, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 68, 472, 69, 471, 69, 472, 68, 472, 67, 473, 67, 473, 67, 472, 68, 472, 68, 472, 68, 473, 67, 473, 66, 474, 66, 476, 64, 476, 64, 476, 63, 478, 62, 479, 59, 481, 59, 482, 57, 484, 55, 486, 54, 487, 52, 488, 52, 489, 50, 492, 47, 494, 45, 497, 42, 499, 38, 505, 33, 512, 27, 520, 17, 523, 17, 526, 10, 242220], 'size': [540, 720]}}

In [6]:
from PIL import Image
import numpy as np
img_path = "datasets/bop23_challenge/datasets/tless/test_primesense/000001/rgb/000017.png"
img = np.array(Image.open(img_path))

In [12]:
import torch
ref_data = {"descriptors": torch.tensor([1, 2, 3])}
data = ref_data["descriptors"]  # In PyTorch, .data is used to access tensor data.
data

tensor([1, 2, 3])

In [6]:
from PIL import Image

scene_id = 1
for frame_id in range(56):
    # Paths to the images
    cnos_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos.png"
    foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_foundpose.png"
    cnos_foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos_foundpose.png"
    groundtruth_result = cnos_foundpose_result
    
    # Open the images
    cnos_image = Image.open(cnos_result)
    foundpose_image = Image.open(foundpose_result)
    cnos_foundpose_image = Image.open(cnos_foundpose_result)
    groundtruth_image = Image.open(groundtruth_result)
    
    # Get the dimensions of the images (assuming they are all the same size)
    width, height = cnos_image.size
    
    # Crop the right half of each image
    right_box = (width // 2, 0, width, height)
    cnos_image_cropped = cnos_image.crop(right_box)
    foundpose_image_cropped = foundpose_image.crop(right_box)
    cnos_foundpose_image_cropped = cnos_foundpose_image.crop(right_box)
    
    # Resize the groundtruth image to match the dimensions of the cropped right half
    groundtruth_image_resized = groundtruth_image.resize((width // 2, height))
    
    # Combine the groundtruth image and the right half of the cnos image side by side
    combined_image = Image.new('RGB', (width, height))
    combined_image.paste(groundtruth_image_resized, (0, 0))
    combined_image.paste(cnos_image_cropped, (width // 2, 0))
    
    # Create a new image with enough space to hold all four images in a 2x2 grid
    stacked_image = Image.new('RGB', (width, height * 2))
    
    # Paste the combined image at the top-left
    stacked_image.paste(combined_image, (0, 0))
    
    # Paste the foundpose_image_cropped at the top-right
    stacked_image.paste(foundpose_image_cropped, (width // 2, 0))
    
    # Paste the cnos_foundpose_image_cropped at the bottom-left
    stacked_image.paste(cnos_foundpose_image_cropped, (0, height))
    
    # Paste the groundtruth_image_resized again at the bottom-right
    stacked_image.paste(groundtruth_image_resized, (width // 2, height))
    
    # Save the stacked image
    output_path = f"cnos_foundpose_analysis/output_images/{frame_id:06d}_{scene_id:06d}_stacked.png"
    stacked_image.save(output_path)

print("Stacking completed for all frames.")


Stacking completed for all frames.


In [13]:
from PIL import Image, ImageDraw, ImageFont
import os

# Load a larger font for the text
font_size = 60  # Increased from the default size (usually around 12-14)
try:
    font = ImageFont.truetype("arial.ttf", font_size)  # You may need to specify the path to a font file
except IOError:
    font = ImageFont.load_default()
    # If using Pillow version < 9.0, use this:
    # font = ImageFont.load_default().font.font_variant(size=font_size)
    # For Pillow version 9.0+, use this:
    font = ImageFont.load_default().font_variant(size=font_size)

scene_id = 1
for frame_id in range(56):
    # Paths to the images
    cnos_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos.png"
    foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_foundpose.png"
    cnos_foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos_foundpose.png"
    
    # Open the images
    cnos_image = Image.open(cnos_result)
    foundpose_image = Image.open(foundpose_result)
    cnos_foundpose_image = Image.open(cnos_foundpose_result)
    
    # Get the dimensions of the images (assuming they are all the same size)
    width, height = cnos_image.size
    
    # Create an ImageDraw object for each image to add text
    draw_cnos = ImageDraw.Draw(cnos_image)
    draw_foundpose = ImageDraw.Draw(foundpose_image)
    draw_cnos_foundpose = ImageDraw.Draw(cnos_foundpose_image)
    
    # Define text positions and content
    text_position = (20, 20)  # Top-left corner with some padding
    text_color = "white"  # White text color
    
    # Add text to each image
    draw_cnos.text(text_position, "CNOS", fill=text_color, font=font)
    draw_foundpose.text(text_position, "Foundpose", fill=text_color, font=font)
    draw_cnos_foundpose.text(text_position, "CNOS + Foundpose", fill=text_color, font=font)
    
    # Create a new image with enough space to hold all three images vertically
    stacked_image = Image.new('RGB', (width, height * 3))
    
    # Paste the images into the new image
    stacked_image.paste(cnos_image, (0, 0))
    stacked_image.paste(foundpose_image, (0, height))
    stacked_image.paste(cnos_foundpose_image, (0, height * 2))
    
    # Save the stacked image
    output_dir = "cnos_foundpose_analysis/output_final_images"
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f"{frame_id:06d}_{scene_id:06d}_stacked.png")
    stacked_image.save(output_path)

print("Stacking completed for all frames.")

Stacking completed for all frames.


In [10]:
from PIL import Image, ImageDraw, ImageFont

# Define the path to a TrueType font file
font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"  # Adjust this path as needed

# Load the font with a larger size
font_size = 80  # You can adjust this size if needed
font = ImageFont.truetype(font_path, font_size)

scene_id = 1
for frame_id in range(59):
    # Paths to the images
    cnos_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos.png"
    foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_foundpose.png"
    cnos_foundpose_result = f"cnos_foundpose_analysis/output_images/{scene_id:06d}_{frame_id:06d}_cnos_foundpose.png"
    
    # Open the images
    cnos_image = Image.open(cnos_result)
    foundpose_image = Image.open(foundpose_result)
    cnos_foundpose_image = Image.open(cnos_foundpose_result)
    
    # Get the dimensions of the images (assuming they are all the same size)
    width, height = cnos_image.size
    
    # Create an ImageDraw object for each image to add text
    draw_cnos = ImageDraw.Draw(cnos_image)
    draw_foundpose = ImageDraw.Draw(foundpose_image)
    draw_cnos_foundpose = ImageDraw.Draw(cnos_foundpose_image)
    
    # Define text content
    text_color = "white"  # White text color
    
    # Calculate the position for the top-right corner
    cnos_text = "CNOS"
    foundpose_text = "Foundpose"
    cnos_foundpose_text = "CNOS + Foundpose"
    
    # Get text sizes
    cnos_text_size = draw_cnos.textsize(cnos_text, font=font)
    foundpose_text_size = draw_foundpose.textsize(foundpose_text, font=font)
    cnos_foundpose_text_size = draw_cnos_foundpose.textsize(cnos_foundpose_text, font=font)
    
    # Calculate the positions for the top-right corner
    cnos_position = (width - cnos_text_size[0] - 10, 10)
    foundpose_position = (width - foundpose_text_size[0] - 10, 10)
    cnos_foundpose_position = (width - cnos_foundpose_text_size[0] - 10, 10)
    
    # Add text to each image at the calculated positions
    draw_cnos.text(cnos_position, cnos_text, fill=text_color, font=font)
    draw_foundpose.text(foundpose_position, foundpose_text, fill=text_color, font=font)
    draw_cnos_foundpose.text(cnos_foundpose_position, cnos_foundpose_text, fill=text_color, font=font)
    
    # Create a new image with enough space to hold all three images vertically
    stacked_image = Image.new('RGB', (width, height * 3))
    
    # Paste the images into the new image
    stacked_image.paste(cnos_image, (0, 0))
    stacked_image.paste(foundpose_image, (0, height))
    stacked_image.paste(cnos_foundpose_image, (0, height * 2))
    
    # Save the stacked image
    output_path = f"cnos_foundpose_analysis/output_final_images/{frame_id:06d}_{scene_id:06d}_stacked.png"
    stacked_image.save(output_path)

print("Stacking completed for all frames.")


AttributeError: 'ImageDraw' object has no attribute 'textsize'